# Generated by Django 3.2.7 on 2021-09-22 07:30

import article.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kateqoriya:')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('title', models.CharField(max_length=50, verbose_name='başlıq')),
                ('content', models.TextField(max_length=5000, verbose_name='məzmun')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='sonuncu dəfə yenilənib')),
                ('drafted', models.BooleanField(default=False, verbose_name='qaralama')),
                ('photo', models.ImageField(blank=True, upload_to=article.models.photo_upload, verbose_name='şəkil')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='müəllif')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='article.category', verbose_name='Kateqoriya')),
            ],
        ),
    ]
